"""Unit tests for the workflow orchestration generator."""

from __future__ import annotations

from openlattice.generators.workflow_gen import generate
from openlattice.ir import LatticeSpec, WorkflowDef, WorkflowStep


def test_dedups_repeated_step_names_across_workflows() -> None:
    spec = LatticeSpec(
        workflows=[
            WorkflowDef(
                name="Checkout",
                steps=[WorkflowStep(name="validate_cart"), WorkflowStep(name="charge_payment")],
            ),
            WorkflowDef(
                name="Refund",
                steps=[WorkflowStep(name="charge_payment"), WorkflowStep(name="notify_user")],
            ),
        ]
    )
    output = generate(spec)

    assert output.count("async def charge_payment() -> None:") == 1
    assert output.count("async def validate_cart() -> None:") == 1
    assert output.count("async def notify_user() -> None:") == 1


def test_orchestrator_calls_steps_in_declared_order() -> None:
    spec = LatticeSpec(
        workflows=[
            WorkflowDef(
                name="Checkout",
                steps=[
                    WorkflowStep(name="validate_cart"),
                    WorkflowStep(name="reserve_inventory"),
                    WorkflowStep(name="charge_payment"),
                ],
            ),
        ]
    )
    output = generate(spec)

    orchestrator_start = output.index("async def checkout() -> None:")
    orchestrator_body = output[orchestrator_start:]
    assert orchestrator_body.index("await validate_cart()") < orchestrator_body.index(
        "await reserve_inventory()"
    )
    assert orchestrator_body.index("await reserve_inventory()") < orchestrator_body.index(
        "await charge_payment()"
    )


def test_empty_workflows_produces_valid_minimal_string() -> None:
    spec = LatticeSpec(workflows=[])
    output = generate(spec)

    assert output == "# Generated by OpenLattice — do not edit\n"
