"""Unit tests for the connector client generator."""

from __future__ import annotations

from openlattice.generators.connectors_gen import generate
from openlattice.ir import ConnectorDef, LatticeSpec
from openlattice.parser import parse_string

SLACK_CONNECTOR_SPEC = """
resource "lattice_connector" "slack_notify" {
  name    = "SlackNotify"
  kind    = "http_webhook"
  url     = "https://hooks.slack.com/services/T000/B000/XXXX"
  method  = "POST"
  headers = { "Content-Type" = "application/json" }
  body_template = {
    text = "{{ order_id }} shipped"
  }
}
"""

EXPECTED_SLACK_OUTPUT = """# Generated by OpenLattice — do not edit

import httpx


async def slack_notify(**payload: object) -> None:
    body = {"text": "{{ order_id }} shipped"}
    async with httpx.AsyncClient() as client:
        await client.post(
            "https://hooks.slack.com/services/T000/B000/XXXX",
            json=body,
            headers={"Content-Type": "application/json"},
        )
"""


def test_generates_client_with_headers_and_body_template() -> None:
    spec = parse_string(SLACK_CONNECTOR_SPEC)
    actual = generate(spec)
    assert actual == EXPECTED_SLACK_OUTPUT
    assert "headers={" in actual
    assert "json=body," in actual


def test_generate_is_deterministic() -> None:
    spec = parse_string(SLACK_CONNECTOR_SPEC)
    first = generate(spec)
    second = generate(spec)
    assert first == second, "Connectors generator is non-deterministic"


def test_no_headers_or_body_template_omits_both_kwargs() -> None:
    spec = LatticeSpec(
        connectors=[
            ConnectorDef(
                name="PingHealthcheck",
                kind="http_webhook",
                url="https://example.com/ping",
                method="GET",
            )
        ]
    )
    actual = generate(spec)
    assert "async def ping_healthcheck(**payload: object) -> None:" in actual
    assert "headers=" not in actual
    assert "json=body" not in actual
    assert "body = " not in actual
    assert "await client.get(" in actual


def test_empty_connectors_returns_header_only() -> None:
    spec = LatticeSpec(connectors=[])
    actual = generate(spec)
    assert actual == "# Generated by OpenLattice — do not edit\n"


def test_multiple_connectors_generate_multiple_functions() -> None:
    spec = LatticeSpec(
        connectors=[
            ConnectorDef(
                name="SlackNotify",
                kind="http_webhook",
                url="https://hooks.slack.com/services/T000/B000/XXXX",
                method="POST",
                body_template={"text": "hi"},
            ),
            ConnectorDef(
                name="EmailWebhook",
                kind="http_webhook",
                url="https://example.com/email",
                method="PUT",
            ),
        ]
    )
    actual = generate(spec)
    assert "async def slack_notify(**payload: object) -> None:" in actual
    assert "async def email_webhook(**payload: object) -> None:" in actual
    assert "await client.post(" in actual
    assert "await client.put(" in actual
