"""Unit tests for the workflow orchestration generator."""

from __future__ import annotations

from openlattice.generators.workflow_gen import generate
from openlattice.ir import ConnectorDef, LatticeSpec, WorkflowDef, WorkflowStep


def test_dedups_repeated_step_names_across_workflows() -> None:
    spec = LatticeSpec(
        workflows=[
            WorkflowDef(
                name="Checkout",
                steps=[WorkflowStep(name="validate_cart"), WorkflowStep(name="charge_payment")],
            ),
            WorkflowDef(
                name="Refund",
                steps=[WorkflowStep(name="charge_payment"), WorkflowStep(name="notify_user")],
            ),
        ]
    )
    output = generate(spec)

    assert output.count("async def charge_payment() -> None:") == 1
    assert output.count("async def validate_cart() -> None:") == 1
    assert output.count("async def notify_user() -> None:") == 1


def test_orchestrator_calls_steps_in_declared_order() -> None:
    spec = LatticeSpec(
        workflows=[
            WorkflowDef(
                name="Checkout",
                steps=[
                    WorkflowStep(name="validate_cart"),
                    WorkflowStep(name="reserve_inventory"),
                    WorkflowStep(name="charge_payment"),
                ],
            ),
        ]
    )
    output = generate(spec)

    orchestrator_start = output.index("async def checkout() -> None:")
    orchestrator_body = output[orchestrator_start:]
    assert orchestrator_body.index("await validate_cart()") < orchestrator_body.index(
        "await reserve_inventory()"
    )
    assert orchestrator_body.index("await reserve_inventory()") < orchestrator_body.index(
        "await charge_payment()"
    )


def test_empty_workflows_produces_valid_minimal_string() -> None:
    spec = LatticeSpec(workflows=[])
    output = generate(spec)

    assert output == "# Generated by OpenLattice — do not edit\n"


def test_step_matching_connector_name_has_no_stub_and_imports_connector() -> None:
    spec = LatticeSpec(
        connectors=[
            ConnectorDef(
                name="SlackNotify",
                kind="http_webhook",
                url="https://hooks.slack.com/services/T000/B000/XXXX",
            )
        ],
        workflows=[
            WorkflowDef(
                name="Checkout",
                steps=[WorkflowStep(name="validate_cart"), WorkflowStep(name="slack_notify")],
            ),
        ],
    )
    output = generate(spec)

    # No redundant stub for the connector-backed step.
    assert "async def slack_notify() -> None:" not in output
    # The regular step still gets a stub.
    assert "async def validate_cart() -> None:" in output
    # The orchestrator still calls it, same as any other step.
    orchestrator_start = output.index("async def checkout() -> None:")
    orchestrator_body = output[orchestrator_start:]
    assert "await slack_notify()" in orchestrator_body
    # workflows.py imports the real implementation from connectors.py.
    assert "from .connectors import slack_notify" in output


def test_workflow_without_connector_steps_has_no_connector_import() -> None:
    spec = LatticeSpec(
        connectors=[
            ConnectorDef(
                name="SlackNotify",
                kind="http_webhook",
                url="https://hooks.slack.com/services/T000/B000/XXXX",
            )
        ],
        workflows=[
            WorkflowDef(
                name="Checkout",
                steps=[WorkflowStep(name="validate_cart")],
            ),
        ],
    )
    output = generate(spec)

    assert "from .connectors import" not in output
