"""FastAPI app assembly generator for OpenLattice.

Emits the thin application entrypoint: it creates the FastAPI app and mounts
the router built by routes_gen.py. This file intentionally has no other
responsibilities — schemas live in schemas_gen.py, routes live in
routes_gen.py.
"""

from openlattice.ir import LatticeSpec


def generate(spec: LatticeSpec) -> str:
    """Generate the FastAPI app entrypoint module.

    Args:
        spec: The parsed LatticeSpec IR. App assembly doesn't currently vary
            by spec contents, but the parameter is kept for interface
            consistency with the other generators (schemas_gen, routes_gen,
            events_gen, workflow_gen, queue_gen all take a LatticeSpec).

    Returns:
        A string containing the full Python source of the generated app
        entrypoint module.
    """
    del spec  # unused — app assembly doesn't depend on spec contents

    sections: list[str] = [
        "# Generated by OpenLattice — do not edit",
        "from fastapi import FastAPI\n\nfrom .routes import router",
        'app = FastAPI(title="OpenLattice Generated App")\napp.include_router(router)',
    ]

    return "\n\n".join(sections) + "\n"
