"""Connector client generator for OpenLattice.

Emits one async httpx-based client function per lattice_connector resource.
"""

import json
import re

from openlattice.ir import ConnectorDef, LatticeSpec


def _to_snake_case(name: str) -> str:
    """Convert CamelCase or PascalCase to snake_case."""
    s = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", name)
    s = re.sub(r"([a-z\d])([A-Z])", r"\1_\2", s)
    return s.lower()


def connector_func_name(connector: ConnectorDef) -> str:
    """The name of the generated async client function for a connector."""
    return _to_snake_case(connector.name)


def _dict_literal(d: dict[str, str]) -> str:
    """Render a dict[str, str] as a Python dict literal with double-quoted strings."""
    entries = ", ".join(f"{json.dumps(k)}: {json.dumps(v)}" for k, v in d.items())
    return f"{{{entries}}}"


def _generate_client(connector: ConnectorDef) -> list[str]:
    lines: list[str] = []
    func_name = connector_func_name(connector)
    lines.append(f"async def {func_name}(**payload: object) -> None:")
    if connector.body_template:
        lines.append(f"    body = {_dict_literal(connector.body_template)}")
    lines.append("    async with httpx.AsyncClient() as client:")
    lines.append(f"        await client.{connector.method.lower()}(")
    lines.append(f"            {json.dumps(connector.url)},")
    if connector.body_template:
        lines.append("            json=body,")
    if connector.headers:
        lines.append(f"            headers={_dict_literal(connector.headers)},")
    lines.append("        )")
    return lines


def generate(spec: LatticeSpec) -> str:
    """Generate one async httpx client function per ConnectorDef.

    Args:
        spec: The parsed LatticeSpec IR.

    Returns:
        A string containing the full Python source of the generated connectors
        module. If the spec has no connectors, only the header comment is
        returned.
    """
    header = "# Generated by OpenLattice — do not edit"

    if not spec.connectors:
        return header + "\n"

    prelude = f"{header}\n\nimport httpx"

    client_sections = ["\n".join(_generate_client(connector)) for connector in spec.connectors]
    clients = "\n\n".join(client_sections)

    return f"{prelude}\n\n\n{clients}\n"
