"""Event model generator for OpenLattice.

Emits one Pydantic BaseModel per lattice_event resource in the spec.
"""

from openlattice.ir import EventDef, LatticeSpec

# DSL type → Python type annotation string
# Kept identical to fastapi_gen.py's mapping so event payload fields render the
# same way entity fields do.
_FIELD_TYPE_MAP: dict[str, str] = {
    "uuid": "UUID",
    "int": "int",
    "float": "float",
    "string": "str",
    "bool": "bool",
    "datetime": "datetime",
    "json": "dict",
}

# Types that require specific imports
_IMPORT_TRIGGERS: dict[str, str] = {
    "UUID": "from uuid import UUID",
    "datetime": "from datetime import datetime",
}


def _generate_model(event: EventDef) -> list[str]:
    lines: list[str] = []
    lines.append(f"class {event.name}(BaseModel):")
    if not event.payload:
        lines.append("    pass")
    else:
        for f in event.payload:
            py_type = _FIELD_TYPE_MAP.get(f.type, "str")
            lines.append(f"    {f.name}: {py_type}")
    return lines


def generate(spec: LatticeSpec) -> str:
    """Generate a complete Pydantic events module from a LatticeSpec.

    Args:
        spec: The parsed LatticeSpec IR.

    Returns:
        A string containing the full Python source of the generated event models.
    """
    # Collect which optional import types are actually needed
    needed_types: set[str] = set()
    for event in spec.events:
        for f in event.payload:
            py_type = _FIELD_TYPE_MAP.get(f.type)
            if py_type and py_type in _IMPORT_TRIGGERS:
                needed_types.add(py_type)

    sections: list[str] = []

    # Header
    sections.append("# Generated by OpenLattice — do not edit")

    if not spec.events:
        # Nothing to emit — keep the file to just the header rather than
        # importing BaseModel with no models to define.
        return "\n\n".join(sections) + "\n"

    # Imports — stdlib first, then third-party (PEP 8)
    import_stdlib: list[str] = []
    if "UUID" in needed_types:
        import_stdlib.append("from uuid import UUID")
    if "datetime" in needed_types:
        import_stdlib.append("from datetime import datetime")
    import_stdlib.sort()

    import_thirdparty: list[str] = ["from pydantic import BaseModel"]

    import_lines: list[str] = []
    if import_stdlib:
        import_lines.extend(import_stdlib)
        import_lines.append("")
    import_lines.extend(import_thirdparty)

    sections.append("\n".join(import_lines))

    # Pydantic models
    model_sections: list[str] = []
    for event in spec.events:
        model_lines = _generate_model(event)
        model_sections.append("\n".join(model_lines))

    # Join header + imports with a single blank line, then drop to a double
    # blank line before the first class (PEP 8 / ruff's isort expects two
    # blank lines when a class/def follows an import block directly), and a
    # single blank line between subsequent classes.
    prelude = "\n\n".join(sections)
    models = "\n\n".join(model_sections)
    return f"{prelude}\n\n\n{models}\n"
