"""FastAPI generator for OpenLattice."""

import re

from openlattice.ir import ApiDef, EntityDef, LatticeSpec

# DSL type → Python type annotation string
_FIELD_TYPE_MAP: dict[str, str] = {
    "uuid": "UUID",
    "int": "int",
    "float": "float",
    "string": "str",
    "bool": "bool",
    "datetime": "datetime",
    "json": "dict",
}

# Types that require specific imports
_IMPORT_TRIGGERS: dict[str, str] = {
    "UUID": "from uuid import UUID",
    "datetime": "from datetime import datetime",
}


def _is_collection_endpoint(api: ApiDef) -> bool:
    """True for GET endpoints with no path params — these return a list."""
    return (
        api.method.upper() == "GET"
        and not _extract_path_params(api.path)
        and bool(api.output_entity)
    )


def _to_snake_case(name: str) -> str:
    """Convert CamelCase or PascalCase to snake_case."""
    s = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", name)
    s = re.sub(r"([a-z\d])([A-Z])", r"\1_\2", s)
    return s.lower()


def _extract_path_params(path: str) -> list[str]:
    """Return a list of parameter names embedded in a URL template, e.g. /orders/{id} → ['id']."""
    return re.findall(r"\{(\w+)\}", path)


def _entity_has_uuid_id(entity_name: str | None, entities: list[EntityDef]) -> bool:
    """Return True if the named entity has a field named 'id' of type 'uuid'."""
    if entity_name is None:
        return False
    for entity in entities:
        if entity.name == entity_name:
            for field in entity.fields:
                if field.name == "id" and field.type == "uuid":
                    return True
    return False


def _generate_model(entity: EntityDef) -> list[str]:
    lines: list[str] = []
    lines.append(f"class {entity.name}(BaseModel):")
    if not entity.fields:
        lines.append("    pass")
    else:
        for f in entity.fields:
            py_type = _FIELD_TYPE_MAP.get(f.type, "str")
            lines.append(f"    {f.name}: {py_type}")
    return lines


def _generate_route(api: ApiDef, entities: list[EntityDef]) -> list[str]:
    lines: list[str] = []

    method = api.method.lower()
    func_name = _to_snake_case(api.name)
    path_params = _extract_path_params(api.path)

    is_collection = _is_collection_endpoint(api)

    # response_model: List[X] for collection GETs, X for single-resource routes
    response_model_part = ""
    if api.output_entity:
        rm = f"List[{api.output_entity}]" if is_collection else api.output_entity
        response_model_part = f", response_model={rm}"

    lines.append(f'@router.{method}("{api.path}"{response_model_part})')

    # Build parameter list
    params: list[str] = []

    # Path parameters — typed UUID if the relevant entity has id: uuid, else str
    ref_entity = api.output_entity or api.input_entity
    use_uuid_for_path = _entity_has_uuid_id(ref_entity, entities)
    for param in path_params:
        param_type = "UUID" if use_uuid_for_path else "str"
        params.append(f"{param}: {param_type}")

    # Body parameter
    if api.input_entity:
        params.append(f"body: {api.input_entity}")

    # Return type annotation
    if api.output_entity:
        return_type = f"List[{api.output_entity}]" if is_collection else api.output_entity
    else:
        return_type = "None"

    param_str = ", ".join(params)
    lines.append(f"async def {func_name}({param_str}) -> {return_type}:")
    lines.append('    raise NotImplementedError("Implement business logic here")')

    return lines


def generate(spec: LatticeSpec) -> str:
    """Generate a complete, runnable FastAPI Python source file from a LatticeSpec.

    Args:
        spec: The parsed LatticeSpec IR.

    Returns:
        A string containing the full Python source of the generated FastAPI application.
    """
    # Collect which optional import types are actually needed
    needed_types: set[str] = set()
    for entity in spec.entities:
        for f in entity.fields:
            py_type = _FIELD_TYPE_MAP.get(f.type)
            if py_type and py_type in _IMPORT_TRIGGERS:
                needed_types.add(py_type)

    # Path params typed UUID also pull in the UUID import
    for api in spec.apis:
        path_params = _extract_path_params(api.path)
        if path_params:
            ref_entity = api.output_entity or api.input_entity
            if _entity_has_uuid_id(ref_entity, spec.entities):
                needed_types.add("UUID")

    sections: list[str] = []

    # Header
    sections.append("# Generated by OpenLattice — do not edit")

    has_collection = any(_is_collection_endpoint(api) for api in spec.apis)

    # Imports — stdlib first, then third-party (PEP 8)
    import_stdlib: list[str] = []
    if "UUID" in needed_types:
        import_stdlib.append("from uuid import UUID")
    if "datetime" in needed_types:
        import_stdlib.append("from datetime import datetime")
    if has_collection:
        import_stdlib.append("from typing import List")
    import_stdlib.sort()

    import_thirdparty: list[str] = [
        "from fastapi import APIRouter, FastAPI",
        "from pydantic import BaseModel",
    ]

    import_lines: list[str] = []
    if import_stdlib:
        import_lines.extend(import_stdlib)
        import_lines.append("")
    import_lines.extend(import_thirdparty)

    sections.append("\n".join(import_lines))

    # App and router
    sections.append('app = FastAPI(title="OpenLattice Generated App")')
    sections.append("router = APIRouter()")

    # Pydantic models
    for entity in spec.entities:
        model_lines = _generate_model(entity)
        sections.append("\n".join(model_lines))

    # Routes
    for api in spec.apis:
        route_lines = _generate_route(api, spec.entities)
        sections.append("\n".join(route_lines))

    # Mount router
    sections.append("app.include_router(router)")

    # Join with double newlines between top-level blocks
    return "\n\n".join(sections) + "\n"
