"""Queue/task infrastructure generator for OpenLattice."""

import re

from openlattice.ir import LatticeSpec, QueueDef


def _to_snake_case(name: str) -> str:
    """Convert CamelCase or PascalCase to snake_case."""
    s = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", name)
    s = re.sub(r"([a-z\d])([A-Z])", r"\1_\2", s)
    return s.lower()


def _handler_name(queue: QueueDef) -> str:
    return f"{_to_snake_case(queue.name)}_handler"


def _generate_handler(queue: QueueDef) -> list[str]:
    lines: list[str] = []
    lines.append(f"async def {_handler_name(queue)}(message: dict) -> None:")
    lines.append('    raise NotImplementedError("Implement business logic here")')
    return lines


def _generate_registry(queues: list[QueueDef]) -> list[str]:
    lines: list[str] = ["QUEUES = {"]
    for queue in queues:
        lines.append(f'    "{queue.name}": {{')
        lines.append(f'        "handler": {_handler_name(queue)},')
        lines.append(f'        "retries": {queue.retries!r},')
        lines.append(f'        "message_type": {queue.message_type!r},')
        lines.append(f'        "dlq": {queue.dlq!r},')
        lines.append("    },")
    lines.append("}")
    return lines


def generate(spec: LatticeSpec) -> str:
    """Generate queue task stubs and a queue registry from a LatticeSpec.

    Args:
        spec: The parsed LatticeSpec IR.

    Returns:
        A string containing the full Python source of the generated queue
        task stubs and registry. If the spec has no queues, only the
        header comment is returned.
    """
    sections: list[str] = ["# Generated by OpenLattice — do not edit"]

    if not spec.queues:
        return sections[0] + "\n"

    for queue in spec.queues:
        sections.append("\n".join(_generate_handler(queue)))

    sections.append("\n".join(_generate_registry(spec.queues)))

    return "\n\n".join(sections) + "\n"
