"""FastAPI route generator for OpenLattice.

Emits an APIRouter plus one route handler per lattice_api resource in the
spec. Handlers reference Pydantic request/response models imported from
schemas_gen.py's output (.schemas).
"""

import re

from openlattice.ir import ApiDef, EntityDef, LatticeSpec


def _is_collection_endpoint(api: ApiDef) -> bool:
    """True for GET endpoints with no path params — these return a list."""
    return (
        api.method.upper() == "GET"
        and not _extract_path_params(api.path)
        and bool(api.output_entity)
    )


def _to_snake_case(name: str) -> str:
    """Convert CamelCase or PascalCase to snake_case."""
    s = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", name)
    s = re.sub(r"([a-z\d])([A-Z])", r"\1_\2", s)
    return s.lower()


def _extract_path_params(path: str) -> list[str]:
    """Return a list of parameter names embedded in a URL template, e.g. /orders/{id} → ['id']."""
    return re.findall(r"\{(\w+)\}", path)


def _entity_has_uuid_id(entity_name: str | None, entities: list[EntityDef]) -> bool:
    """Return True if the named entity has a field named 'id' of type 'uuid'."""
    if entity_name is None:
        return False
    for entity in entities:
        if entity.name == entity_name:
            for field in entity.fields:
                if field.name == "id" and field.type == "uuid":
                    return True
    return False


def _referenced_entities(spec: LatticeSpec) -> list[str]:
    """Entity names referenced as an API's input/output, sorted alphabetically.

    Only entities actually used as a request/response type need to be
    imported from .schemas — this mirrors the "only import what's needed"
    pattern used for stdlib imports below. Sorted (rather than left in
    spec.entities declaration order) to match isort/ruff's expectation that
    names within an import statement are alphabetized.
    """
    referenced: set[str] = set()
    for api in spec.apis:
        if api.input_entity:
            referenced.add(api.input_entity)
        if api.output_entity:
            referenced.add(api.output_entity)
    return sorted(referenced)


def _generate_route(api: ApiDef, entities: list[EntityDef]) -> list[str]:
    lines: list[str] = []

    method = api.method.lower()
    func_name = _to_snake_case(api.name)
    path_params = _extract_path_params(api.path)

    is_collection = _is_collection_endpoint(api)

    # response_model: List[X] for collection GETs, X for single-resource routes
    response_model_part = ""
    if api.output_entity:
        rm = f"List[{api.output_entity}]" if is_collection else api.output_entity
        response_model_part = f", response_model={rm}"

    lines.append(f'@router.{method}("{api.path}"{response_model_part})')

    # Build parameter list
    params: list[str] = []

    # Path parameters — typed UUID if the relevant entity has id: uuid, else str
    ref_entity = api.output_entity or api.input_entity
    use_uuid_for_path = _entity_has_uuid_id(ref_entity, entities)
    for param in path_params:
        param_type = "UUID" if use_uuid_for_path else "str"
        params.append(f"{param}: {param_type}")

    # Body parameter
    if api.input_entity:
        params.append(f"body: {api.input_entity}")

    # Return type annotation
    if api.output_entity:
        return_type = f"List[{api.output_entity}]" if is_collection else api.output_entity
    else:
        return_type = "None"

    param_str = ", ".join(params)
    lines.append(f"async def {func_name}({param_str}) -> {return_type}:")
    lines.append('    raise NotImplementedError("Implement business logic here")')

    return lines


def generate(spec: LatticeSpec) -> str:
    """Generate a complete FastAPI router module from a LatticeSpec.

    Args:
        spec: The parsed LatticeSpec IR.

    Returns:
        A string containing the full Python source of the generated
        APIRouter and route handlers.
    """
    # Collect which optional import types are actually needed
    needed_types: set[str] = set()
    for api in spec.apis:
        path_params = _extract_path_params(api.path)
        if path_params:
            ref_entity = api.output_entity or api.input_entity
            if _entity_has_uuid_id(ref_entity, spec.entities):
                needed_types.add("UUID")

    sections: list[str] = []

    # Header
    sections.append("# Generated by OpenLattice — do not edit")

    has_collection = any(_is_collection_endpoint(api) for api in spec.apis)

    # Imports — stdlib first, then third-party, then local (PEP 8)
    import_stdlib: list[str] = []
    if "UUID" in needed_types:
        import_stdlib.append("from uuid import UUID")
    if has_collection:
        import_stdlib.append("from typing import List")
    import_stdlib.sort()

    import_thirdparty: list[str] = ["from fastapi import APIRouter"]

    referenced_entities = _referenced_entities(spec)
    import_local: list[str] = []
    if referenced_entities:
        import_local.append(f"from .schemas import {', '.join(referenced_entities)}")

    import_lines: list[str] = []
    if import_stdlib:
        import_lines.extend(import_stdlib)
        import_lines.append("")
    import_lines.extend(import_thirdparty)
    if import_local:
        import_lines.append("")
        import_lines.extend(import_local)

    sections.append("\n".join(import_lines))

    # Router
    sections.append("router = APIRouter()")

    # Routes
    for api in spec.apis:
        route_lines = _generate_route(api, spec.entities)
        sections.append("\n".join(route_lines))

    # Join with double newlines between top-level blocks
    return "\n\n".join(sections) + "\n"
