"""Pydantic schema generator for OpenLattice.

Emits one Pydantic BaseModel per lattice_entity resource in the spec, for use
as FastAPI request/response schemas (see routes_gen.py, which imports these
models).
"""

from openlattice.ir import EntityDef, LatticeSpec

# DSL type → Python type annotation string
_FIELD_TYPE_MAP: dict[str, str] = {
    "uuid": "UUID",
    "int": "int",
    "float": "float",
    "string": "str",
    "bool": "bool",
    "datetime": "datetime",
    "json": "dict",
}

# Types that require specific imports
_IMPORT_TRIGGERS: dict[str, str] = {
    "UUID": "from uuid import UUID",
    "datetime": "from datetime import datetime",
}


def _generate_model(entity: EntityDef) -> list[str]:
    lines: list[str] = []
    lines.append(f"class {entity.name}(BaseModel):")
    if not entity.fields:
        lines.append("    pass")
    else:
        for f in entity.fields:
            py_type = _FIELD_TYPE_MAP.get(f.type, "str")
            lines.append(f"    {f.name}: {py_type}")
    return lines


def generate(spec: LatticeSpec) -> str:
    """Generate a complete Pydantic schemas module from a LatticeSpec.

    Args:
        spec: The parsed LatticeSpec IR.

    Returns:
        A string containing the full Python source of the generated Pydantic
        entity models.
    """
    sections: list[str] = []

    sections.append("# Generated by OpenLattice — do not edit")

    if not spec.entities:
        return "\n\n".join(sections) + "\n"

    needed_types: set[str] = set()
    for entity in spec.entities:
        for f in entity.fields:
            py_type = _FIELD_TYPE_MAP.get(f.type)
            if py_type and py_type in _IMPORT_TRIGGERS:
                needed_types.add(py_type)

    import_stdlib: list[str] = []
    if "UUID" in needed_types:
        import_stdlib.append("from uuid import UUID")
    if "datetime" in needed_types:
        import_stdlib.append("from datetime import datetime")
    import_stdlib.sort()

    import_thirdparty: list[str] = ["from pydantic import BaseModel"]

    import_lines: list[str] = []
    if import_stdlib:
        import_lines.extend(import_stdlib)
        import_lines.append("")
    import_lines.extend(import_thirdparty)

    sections.append("\n".join(import_lines))

    model_sections: list[str] = []
    for entity in spec.entities:
        model_lines = _generate_model(entity)
        model_sections.append("\n".join(model_lines))

    # Two blank lines between the import block and the first class definition
    # (PEP 8 / ruff's isort convention), one blank line between classes.
    prelude = "\n\n".join(sections)
    models = "\n\n".join(model_sections)
    return f"{prelude}\n\n\n{models}\n"
