"""SQLAlchemy 2.0 ORM generator for OpenLattice."""

from openlattice.ir import LatticeSpec, EntityDef, FieldDef

# DSL type → (Mapped Python type, mapped_column(...) expression)
# The mapped_column expression is a template; {name} is replaced with the field name.
_FIELD_MAP: dict[str, tuple[str, str]] = {
    "uuid": ("uuid.UUID", "mapped_column(UUID(as_uuid=True))"),
    "int": ("int", "mapped_column(Integer, nullable=False)"),
    "float": ("float", "mapped_column(Float, nullable=False)"),
    "string": ("str", "mapped_column(String, nullable=False)"),
    "bool": ("bool", "mapped_column(Boolean, nullable=False)"),
    "datetime": ("datetime", "mapped_column(DateTime, nullable=False)"),
    "json": ("dict", "mapped_column(JSON, nullable=False)"),
}

# Mapped Python type → import statement (for types needing special imports beyond the base set)
_EXTRA_IMPORTS: dict[str, str] = {
    "datetime": "from datetime import datetime",
}


def _table_name(entity_name: str) -> str:
    """Convert an entity name to a snake_case table name (simple lowercase pluralisation)."""
    # naive pluralisation: just lowercase + 's'
    return entity_name.lower() + "s"


def _generate_class(entity: EntityDef) -> list[str]:
    lines: list[str] = []
    lines.append(f"class {entity.name}(Base):")
    lines.append(f'    __tablename__ = "{_table_name(entity.name)}"')
    lines.append("")

    if not entity.fields:
        lines.append("    pass")
        return lines

    for f in entity.fields:
        if f.type not in _FIELD_MAP:
            # Unknown type — fall back to String
            mapped_type = "str"
            col_expr = "mapped_column(String, nullable=False)"
        else:
            mapped_type, col_expr = _FIELD_MAP[f.type]

        # Special handling for the primary key 'id' of type uuid
        if f.name == "id" and f.type == "uuid":
            col_expr = "mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)"

        lines.append(f"    {f.name}: Mapped[{mapped_type}] = {col_expr}")

    return lines


def generate(spec: LatticeSpec) -> str:
    """Generate a complete SQLAlchemy 2.0 ORM Python source file from a LatticeSpec.

    Args:
        spec: The parsed LatticeSpec IR.

    Returns:
        A string containing the full Python source of the generated ORM models.
    """
    # Determine which extra imports are needed based on field types used
    used_dsl_types: set[str] = set()
    for entity in spec.entities:
        for f in entity.fields:
            used_dsl_types.add(f.type)

    sections: list[str] = []

    # Header
    sections.append("# Generated by OpenLattice — do not edit")

    # Imports
    import_lines: list[str] = ["import uuid"]

    # SQLAlchemy column type imports — only include what's needed
    _sa_type_map: dict[str, str] = {
        "int": "Integer",
        "float": "Float",
        "string": "String",
        "bool": "Boolean",
        "datetime": "DateTime",
        "json": "JSON",
    }
    needed_sa_types: list[str] = [
        _sa_type_map[t]
        for t in ("int", "float", "string", "bool", "datetime", "json")
        if t in used_dsl_types
    ]
    if needed_sa_types:
        import_lines.append(f"from sqlalchemy import {', '.join(needed_sa_types)}")

    # UUID always from postgres dialect if uuid fields exist
    if "uuid" in used_dsl_types:
        import_lines.append("from sqlalchemy.dialects.postgresql import UUID")

    import_lines.append("from sqlalchemy.orm import DeclarativeBase, mapped_column, Mapped")

    # Extra Python-side type imports
    if "datetime" in used_dsl_types:
        import_lines.append("from datetime import datetime")

    sections.append("\n".join(import_lines))

    # Base class
    sections.append("class Base(DeclarativeBase):\n    pass")

    # ORM model classes
    for entity in spec.entities:
        class_lines = _generate_class(entity)
        sections.append("\n".join(class_lines))

    return "\n\n\n".join(sections) + "\n"
