"""Workflow orchestration generator for OpenLattice."""

import re

from openlattice.ir import LatticeSpec, WorkflowDef


def _to_snake_case(name: str) -> str:
    """Convert CamelCase or PascalCase to snake_case."""
    s = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", name)
    s = re.sub(r"([a-z\d])([A-Z])", r"\1_\2", s)
    return s.lower()


def _generate_step_stub(step_name: str) -> list[str]:
    lines: list[str] = []
    lines.append(f"async def {step_name}() -> None:")
    lines.append('    raise NotImplementedError("Implement business logic here")')
    return lines


def _generate_orchestrator(workflow: WorkflowDef) -> list[str]:
    lines: list[str] = []
    func_name = _to_snake_case(workflow.name)
    lines.append(f"async def {func_name}() -> None:")
    lines.append(f'    """Workflow: {workflow.name}"""')
    for step in workflow.steps:
        lines.append(f"    await {step.name}()")
    return lines


def generate(spec: LatticeSpec) -> str:
    """Generate step function stubs and an async orchestrator per WorkflowDef.

    Args:
        spec: The parsed LatticeSpec IR.

    Returns:
        A string containing the full Python source of the generated workflow module.
    """
    sections: list[str] = []

    # Header
    sections.append("# Generated by OpenLattice — do not edit")

    # Step stubs — one per unique step name across all workflows, in first-seen order
    seen_steps: set[str] = set()
    for workflow in spec.workflows:
        for step in workflow.steps:
            if step.name in seen_steps:
                continue
            seen_steps.add(step.name)
            sections.append("\n".join(_generate_step_stub(step.name)))

    # Orchestrators
    for workflow in spec.workflows:
        sections.append("\n".join(_generate_orchestrator(workflow)))

    return "\n\n".join(sections) + "\n"
