# Generated by OpenLattice — do not edit

from datetime import datetime
from uuid import UUID

from pydantic import BaseModel


class OrderCreated(BaseModel):
    order_id: UUID
    user_id: UUID
    total: float

class OrderShipped(BaseModel):
    order_id: UUID
    shipped_at: datetime
