# Generated by OpenLattice — do not edit

async def email_notifications_handler(message: dict) -> None:
    raise NotImplementedError("Implement business logic here")

async def inventory_updates_handler(message: dict) -> None:
    raise NotImplementedError("Implement business logic here")

QUEUES = {
    "email_notifications": {
        "handler": email_notifications_handler,
        "retries": 5,
        "message_type": None,
        "dlq": False,
    },
    "inventory_updates": {
        "handler": inventory_updates_handler,
        "retries": 3,
        "message_type": None,
        "dlq": False,
    },
}
