# Generated by OpenLattice — do not edit

async def validate_cart() -> None:
    raise NotImplementedError("Implement business logic here")

async def reserve_inventory() -> None:
    raise NotImplementedError("Implement business logic here")

async def charge_payment() -> None:
    raise NotImplementedError("Implement business logic here")

async def create_order() -> None:
    raise NotImplementedError("Implement business logic here")

async def publish_order_created() -> None:
    raise NotImplementedError("Implement business logic here")

async def checkout() -> None:
    """Workflow: Checkout"""
    await validate_cart()
    await reserve_inventory()
    await charge_payment()
    await create_order()
    await publish_order_created()
