# Generated by OpenLattice — do not edit

from typing import List
from uuid import UUID

from fastapi import APIRouter

from .schemas import Order

router = APIRouter()

@router.post("/orders", response_model=Order)
async def create_order(body: Order) -> Order:
    raise NotImplementedError("Implement business logic here")

@router.get("/orders/{id}", response_model=Order)
async def get_order(id: UUID) -> Order:
    raise NotImplementedError("Implement business logic here")

@router.get("/orders", response_model=List[Order])
async def list_orders() -> List[Order]:
    raise NotImplementedError("Implement business logic here")
