# Generated by OpenLattice — do not edit

from uuid import UUID

from pydantic import BaseModel


class Order(BaseModel):
    id: UUID
    amount: int
    status: str

class Product(BaseModel):
    id: UUID
    name: str
    price: float
