# Generated by OpenLattice — do not edit

from typing import List
from uuid import UUID

from fastapi import APIRouter, FastAPI
from pydantic import BaseModel

app = FastAPI(title="OpenLattice Generated App")

router = APIRouter()

class Order(BaseModel):
    id: UUID
    amount: int
    status: str

class Product(BaseModel):
    id: UUID
    name: str
    price: float

@router.post("/orders", response_model=Order)
async def create_order(body: Order) -> Order:
    raise NotImplementedError("Implement business logic here")

@router.get("/orders/{id}", response_model=Order)
async def get_order(id: UUID) -> Order:
    raise NotImplementedError("Implement business logic here")

@router.get("/orders", response_model=List[Order])
async def list_orders() -> List[Order]:
    raise NotImplementedError("Implement business logic here")

app.include_router(router)
